RDMSOL: 125.0
SoilProfileDescription:
  GroundWater: false
  PFFieldCapacity: 2.0
  PFWiltingPoint: 4.2
  SoilLayers:
  - CNRatioSOMI: 9.0
    CONDfromPF:
    - 0.0
    - 1.999
    - 1.0
    - 1.381
    - 1.3
    - 1.004
    - 1.5
    - 0.708
    - 1.7
    - 0.1
    - 2.0
    - -1.125
    - 2.4
    - -3.06
    - 2.7
    - -3.959
    - 3.0
    - -4.62
    - 3.4
    - -5.328
    - 3.7
    - -6.0
    - 4.0
    - -6.585
    - 4.2
    - -7.201
    CRAIRC: 0.09
    FSOMI: 0.02
    RHOD: 1.406
    SMfromPF:
    - -1.0
    - 0.39
    - 1.0
    - 0.38
    - 1.3
    - 0.36
    - 1.5
    - 0.332
    - 2.0
    - 0.185
    - 2.4
    - 0.086
    - 2.7
    - 0.056
    - 3.4
    - 0.04
    - 4.2
    - 0.04
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 11.0
    CONDfromPF:
    - 0.0
    - 1.999
    - 1.0
    - 1.381
    - 1.3
    - 1.004
    - 1.5
    - 0.708
    - 1.7
    - 0.1
    - 2.0
    - -1.125
    - 2.4
    - -3.06
    - 2.7
    - -3.959
    - 3.0
    - -4.62
    - 3.4
    - -5.328
    - 3.7
    - -6.0
    - 4.0
    - -6.585
    - 4.2
    - -7.201
    CRAIRC: 0.09
    FSOMI: 0.015
    RHOD: 1.42
    SMfromPF:
    - -1.0
    - 0.39
    - 1.0
    - 0.38
    - 1.3
    - 0.36
    - 1.5
    - 0.332
    - 2.0
    - 0.185
    - 2.4
    - 0.086
    - 2.7
    - 0.056
    - 3.4
    - 0.04
    - 4.2
    - 0.04
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 10.0
  - CNRatioSOMI: 12.6
    CONDfromPF:
    - 0.0
    - 1.999
    - 1.0
    - 1.381
    - 1.3
    - 1.004
    - 1.5
    - 0.708
    - 1.7
    - 0.1
    - 2.0
    - -1.125
    - 2.4
    - -3.06
    - 2.7
    - -3.959
    - 3.0
    - -4.62
    - 3.4
    - -5.328
    - 3.7
    - -6.0
    - 4.0
    - -6.585
    - 4.2
    - -7.201
    CRAIRC: 0.09
    FSOMI: 0.011
    RHOD: 1.432
    SMfromPF:
    - -1.0
    - 0.39
    - 1.0
    - 0.38
    - 1.3
    - 0.36
    - 1.5
    - 0.332
    - 2.0
    - 0.185
    - 2.4
    - 0.086
    - 2.7
    - 0.056
    - 3.4
    - 0.04
    - 4.2
    - 0.04
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 10.0
  - CNRatioSOMI: 14.31
    CONDfromPF:
    - 0.0
    - 1.999
    - 1.0
    - 1.381
    - 1.3
    - 1.004
    - 1.5
    - 0.708
    - 1.7
    - 0.1
    - 2.0
    - -1.125
    - 2.4
    - -3.06
    - 2.7
    - -3.959
    - 3.0
    - -4.62
    - 3.4
    - -5.328
    - 3.7
    - -6.0
    - 4.0
    - -6.585
    - 4.2
    - -7.201
    CRAIRC: 0.09
    FSOMI: 0.0076
    RHOD: 1.45
    SMfromPF:
    - -1.0
    - 0.39
    - 1.0
    - 0.38
    - 1.3
    - 0.36
    - 1.5
    - 0.332
    - 2.0
    - 0.185
    - 2.4
    - 0.086
    - 2.7
    - 0.056
    - 3.4
    - 0.04
    - 4.2
    - 0.04
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 16.42
    CONDfromPF:
    - 0.0
    - 1.999
    - 1.0
    - 1.381
    - 1.3
    - 1.004
    - 1.5
    - 0.708
    - 1.7
    - 0.1
    - 2.0
    - -1.125
    - 2.4
    - -3.06
    - 2.7
    - -3.959
    - 3.0
    - -4.62
    - 3.4
    - -5.328
    - 3.7
    - -6.0
    - 4.0
    - -6.585
    - 4.2
    - -7.201
    CRAIRC: 0.09
    FSOMI: 0.0038
    RHOD: 1.505
    SMfromPF:
    - -1.0
    - 0.39
    - 1.0
    - 0.38
    - 1.3
    - 0.36
    - 1.5
    - 0.332
    - 2.0
    - 0.185
    - 2.4
    - 0.086
    - 2.7
    - 0.056
    - 3.4
    - 0.04
    - 4.2
    - 0.04
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 18.0
    CONDfromPF:
    - 0.0
    - 1.999
    - 1.0
    - 1.381
    - 1.3
    - 1.004
    - 1.5
    - 0.708
    - 1.7
    - 0.1
    - 2.0
    - -1.125
    - 2.4
    - -3.06
    - 2.7
    - -3.959
    - 3.0
    - -4.62
    - 3.4
    - -5.328
    - 3.7
    - -6.0
    - 4.0
    - -6.585
    - 4.2
    - -7.201
    CRAIRC: 0.09
    FSOMI: 0.001
    RHOD: 1.537
    SMfromPF:
    - -1.0
    - 0.39
    - 1.0
    - 0.38
    - 1.3
    - 0.36
    - 1.5
    - 0.332
    - 2.0
    - 0.185
    - 2.4
    - 0.086
    - 2.7
    - 0.056
    - 3.4
    - 0.04
    - 4.2
    - 0.04
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 18.0
    CONDfromPF:
    - 0.0
    - 1.999
    - 1.0
    - 1.381
    - 1.3
    - 1.004
    - 1.5
    - 0.708
    - 1.7
    - 0.1
    - 2.0
    - -1.125
    - 2.4
    - -3.06
    - 2.7
    - -3.959
    - 3.0
    - -4.62
    - 3.4
    - -5.328
    - 3.7
    - -6.0
    - 4.0
    - -6.585
    - 4.2
    - -7.201
    CRAIRC: 0.09
    FSOMI: 0.001
    RHOD: 1.537
    SMfromPF:
    - -1.0
    - 0.39
    - 1.0
    - 0.38
    - 1.3
    - 0.36
    - 1.5
    - 0.332
    - 2.0
    - 0.185
    - 2.4
    - 0.086
    - 2.7
    - 0.056
    - 3.4
    - 0.04
    - 4.2
    - 0.04
    - 6.0
    - 0.04
    Soil_pH: 7.4
    SubSoilType: null
    Thickness: 25.0
  SurfaceConductivity: 75.0
