RDMSOL: 125.0
SoilProfileDescription:
  GroundWater: false
  PFFieldCapacity: 2.0
  PFWiltingPoint: 4.2
  SoilLayers:
  - CNRatioSOMI: 9.0
    CONDfromPF:
    - 0.0
    - 1.408
    - 1.0
    - 0.167
    - 1.3
    - -0.215
    - 1.5
    - -0.638
    - 1.7
    - -0.854
    - 2.0
    - -1.155
    - 2.4
    - -1.796
    - 2.7
    - -2.26
    - 3.0
    - -2.745
    - 3.4
    - -3.357
    - 3.7
    - -3.824
    - 4.0
    - -4.276
    - 4.2
    - -4.678
    CRAIRC: 0.06
    FSOMI: 0.02
    RHOD: 1.406
    SMfromPF:
    - -1.0
    - 0.41
    - 1.0
    - 0.398
    - 1.3
    - 0.389
    - 1.5
    - 0.38
    - 2.0
    - 0.34
    - 2.4
    - 0.287
    - 2.7
    - 0.241
    - 3.4
    - 0.148
    - 4.2
    - 0.104
    - 6.0
    - 0.09
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 11.0
    CONDfromPF:
    - 0.0
    - 1.408
    - 1.0
    - 0.167
    - 1.3
    - -0.215
    - 1.5
    - -0.638
    - 1.7
    - -0.854
    - 2.0
    - -1.155
    - 2.4
    - -1.796
    - 2.7
    - -2.26
    - 3.0
    - -2.745
    - 3.4
    - -3.357
    - 3.7
    - -3.824
    - 4.0
    - -4.276
    - 4.2
    - -4.678
    CRAIRC: 0.06
    FSOMI: 0.015
    RHOD: 1.42
    SMfromPF:
    - -1.0
    - 0.41
    - 1.0
    - 0.398
    - 1.3
    - 0.389
    - 1.5
    - 0.38
    - 2.0
    - 0.34
    - 2.4
    - 0.287
    - 2.7
    - 0.241
    - 3.4
    - 0.148
    - 4.2
    - 0.104
    - 6.0
    - 0.09
    Soil_pH: 7.4
    Thickness: 10.0
  - CNRatioSOMI: 12.6
    CONDfromPF:
    - 0.0
    - 1.408
    - 1.0
    - 0.167
    - 1.3
    - -0.215
    - 1.5
    - -0.638
    - 1.7
    - -0.854
    - 2.0
    - -1.155
    - 2.4
    - -1.796
    - 2.7
    - -2.26
    - 3.0
    - -2.745
    - 3.4
    - -3.357
    - 3.7
    - -3.824
    - 4.0
    - -4.276
    - 4.2
    - -4.678
    CRAIRC: 0.06
    FSOMI: 0.011
    RHOD: 1.432
    SMfromPF:
    - -1.0
    - 0.41
    - 1.0
    - 0.398
    - 1.3
    - 0.389
    - 1.5
    - 0.38
    - 2.0
    - 0.34
    - 2.4
    - 0.287
    - 2.7
    - 0.241
    - 3.4
    - 0.148
    - 4.2
    - 0.104
    - 6.0
    - 0.09
    Soil_pH: 7.4
    Thickness: 10.0
  - CNRatioSOMI: 14.31
    CONDfromPF:
    - 0.0
    - 1.408
    - 1.0
    - 0.167
    - 1.3
    - -0.215
    - 1.5
    - -0.638
    - 1.7
    - -0.854
    - 2.0
    - -1.155
    - 2.4
    - -1.796
    - 2.7
    - -2.26
    - 3.0
    - -2.745
    - 3.4
    - -3.357
    - 3.7
    - -3.824
    - 4.0
    - -4.276
    - 4.2
    - -4.678
    CRAIRC: 0.06
    FSOMI: 0.0076
    RHOD: 1.45
    SMfromPF:
    - -1.0
    - 0.41
    - 1.0
    - 0.398
    - 1.3
    - 0.389
    - 1.5
    - 0.38
    - 2.0
    - 0.34
    - 2.4
    - 0.287
    - 2.7
    - 0.241
    - 3.4
    - 0.148
    - 4.2
    - 0.104
    - 6.0
    - 0.09
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 16.42
    CONDfromPF:
    - 0.0
    - 1.408
    - 1.0
    - 0.167
    - 1.3
    - -0.215
    - 1.5
    - -0.638
    - 1.7
    - -0.854
    - 2.0
    - -1.155
    - 2.4
    - -1.796
    - 2.7
    - -2.26
    - 3.0
    - -2.745
    - 3.4
    - -3.357
    - 3.7
    - -3.824
    - 4.0
    - -4.276
    - 4.2
    - -4.678
    CRAIRC: 0.06
    FSOMI: 0.0038
    RHOD: 1.505
    SMfromPF:
    - -1.0
    - 0.41
    - 1.0
    - 0.398
    - 1.3
    - 0.389
    - 1.5
    - 0.38
    - 2.0
    - 0.34
    - 2.4
    - 0.287
    - 2.7
    - 0.241
    - 3.4
    - 0.148
    - 4.2
    - 0.104
    - 6.0
    - 0.09
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 18.0
    CONDfromPF:
    - 0.0
    - 1.408
    - 1.0
    - 0.167
    - 1.3
    - -0.215
    - 1.5
    - -0.638
    - 1.7
    - -0.854
    - 2.0
    - -1.155
    - 2.4
    - -1.796
    - 2.7
    - -2.26
    - 3.0
    - -2.745
    - 3.4
    - -3.357
    - 3.7
    - -3.824
    - 4.0
    - -4.276
    - 4.2
    - -4.678
    CRAIRC: 0.06
    FSOMI: 0.001
    RHOD: 1.537
    SMfromPF:
    - -1.0
    - 0.41
    - 1.0
    - 0.398
    - 1.3
    - 0.389
    - 1.5
    - 0.38
    - 2.0
    - 0.34
    - 2.4
    - 0.287
    - 2.7
    - 0.241
    - 3.4
    - 0.148
    - 4.2
    - 0.104
    - 6.0
    - 0.09
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 18.0
    CONDfromPF:
    - 0.0
    - 1.408
    - 1.0
    - 0.167
    - 1.3
    - -0.215
    - 1.5
    - -0.638
    - 1.7
    - -0.854
    - 2.0
    - -1.155
    - 2.4
    - -1.796
    - 2.7
    - -2.26
    - 3.0
    - -2.745
    - 3.4
    - -3.357
    - 3.7
    - -3.824
    - 4.0
    - -4.276
    - 4.2
    - -4.678
    CRAIRC: 0.06
    FSOMI: 0.001
    RHOD: 1.537
    SMfromPF:
    - -1.0
    - 0.41
    - 1.0
    - 0.398
    - 1.3
    - 0.389
    - 1.5
    - 0.38
    - 2.0
    - 0.34
    - 2.4
    - 0.287
    - 2.7
    - 0.241
    - 3.4
    - 0.148
    - 4.2
    - 0.104
    - 6.0
    - 0.09
    Soil_pH: 7.4
    SubSoilType: null
    Thickness: 25.0
  SurfaceConductivity: 75.0
