RDMSOL: 125.0
SoilProfileDescription:
  GroundWater: false
  PFFieldCapacity: 2.0
  PFWiltingPoint: 4.2
  SoilLayers:
  - CNRatioSOMI: 9.0
    CONDfromPF:
    - 0.0
    - 1.13
    - 1.0
    - 0.255
    - 1.3
    - 0.097
    - 1.5
    - -0.444
    - 1.7
    - -0.62
    - 2.0
    - -1.19
    - 2.4
    - -2.03
    - 2.7
    - -2.74
    - 3.0
    - -3.387
    - 3.4
    - -4.012
    - 3.7
    - -4.398
    - 4.0
    - -4.795
    - 4.2
    - -4.987
    CRAIRC: 0.1
    FSOMI: 0.02
    RHOD: 1.406
    SMfromPF:
    - -1.0
    - 0.73
    - 1.0
    - 0.675
    - 1.3
    - 0.66
    - 1.5
    - 0.645
    - 2.0
    - 0.59
    - 2.4
    - 0.5
    - 2.7
    - 0.41
    - 3.4
    - 0.22
    - 4.2
    - 0.13
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 11.0
    CONDfromPF:
    - 0.0
    - 1.13
    - 1.0
    - 0.255
    - 1.3
    - 0.097
    - 1.5
    - -0.444
    - 1.7
    - -0.62
    - 2.0
    - -1.19
    - 2.4
    - -2.03
    - 2.7
    - -2.74
    - 3.0
    - -3.387
    - 3.4
    - -4.012
    - 3.7
    - -4.398
    - 4.0
    - -4.795
    - 4.2
    - -4.987
    CRAIRC: 0.1
    FSOMI: 0.015
    RHOD: 1.42
    SMfromPF:
    - -1.0
    - 0.73
    - 1.0
    - 0.675
    - 1.3
    - 0.66
    - 1.5
    - 0.645
    - 2.0
    - 0.59
    - 2.4
    - 0.5
    - 2.7
    - 0.41
    - 3.4
    - 0.22
    - 4.2
    - 0.13
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 10.0
  - CNRatioSOMI: 12.6
    CONDfromPF:
    - 0.0
    - 1.13
    - 1.0
    - 0.255
    - 1.3
    - 0.097
    - 1.5
    - -0.444
    - 1.7
    - -0.62
    - 2.0
    - -1.19
    - 2.4
    - -2.03
    - 2.7
    - -2.74
    - 3.0
    - -3.387
    - 3.4
    - -4.012
    - 3.7
    - -4.398
    - 4.0
    - -4.795
    - 4.2
    - -4.987
    CRAIRC: 0.1
    FSOMI: 0.011
    RHOD: 1.432
    SMfromPF:
    - -1.0
    - 0.73
    - 1.0
    - 0.675
    - 1.3
    - 0.66
    - 1.5
    - 0.645
    - 2.0
    - 0.59
    - 2.4
    - 0.5
    - 2.7
    - 0.41
    - 3.4
    - 0.22
    - 4.2
    - 0.13
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 10.0
  - CNRatioSOMI: 14.31
    CONDfromPF:
    - 0.0
    - 1.13
    - 1.0
    - 0.255
    - 1.3
    - 0.097
    - 1.5
    - -0.444
    - 1.7
    - -0.62
    - 2.0
    - -1.19
    - 2.4
    - -2.03
    - 2.7
    - -2.74
    - 3.0
    - -3.387
    - 3.4
    - -4.012
    - 3.7
    - -4.398
    - 4.0
    - -4.795
    - 4.2
    - -4.987
    CRAIRC: 0.1
    FSOMI: 0.0076
    RHOD: 1.45
    SMfromPF:
    - -1.0
    - 0.73
    - 1.0
    - 0.675
    - 1.3
    - 0.66
    - 1.5
    - 0.645
    - 2.0
    - 0.59
    - 2.4
    - 0.5
    - 2.7
    - 0.41
    - 3.4
    - 0.22
    - 4.2
    - 0.13
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 16.42
    CONDfromPF:
    - 0.0
    - 1.13
    - 1.0
    - 0.255
    - 1.3
    - 0.097
    - 1.5
    - -0.444
    - 1.7
    - -0.62
    - 2.0
    - -1.19
    - 2.4
    - -2.03
    - 2.7
    - -2.74
    - 3.0
    - -3.387
    - 3.4
    - -4.012
    - 3.7
    - -4.398
    - 4.0
    - -4.795
    - 4.2
    - -4.987
    CRAIRC: 0.1
    FSOMI: 0.0038
    RHOD: 1.505
    SMfromPF:
    - -1.0
    - 0.73
    - 1.0
    - 0.675
    - 1.3
    - 0.66
    - 1.5
    - 0.645
    - 2.0
    - 0.59
    - 2.4
    - 0.5
    - 2.7
    - 0.41
    - 3.4
    - 0.22
    - 4.2
    - 0.13
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 18.0
    CONDfromPF:
    - 0.0
    - 1.13
    - 1.0
    - 0.255
    - 1.3
    - 0.097
    - 1.5
    - -0.444
    - 1.7
    - -0.62
    - 2.0
    - -1.19
    - 2.4
    - -2.03
    - 2.7
    - -2.74
    - 3.0
    - -3.387
    - 3.4
    - -4.012
    - 3.7
    - -4.398
    - 4.0
    - -4.795
    - 4.2
    - -4.987
    CRAIRC: 0.1
    FSOMI: 0.001
    RHOD: 1.537
    SMfromPF:
    - -1.0
    - 0.73
    - 1.0
    - 0.675
    - 1.3
    - 0.66
    - 1.5
    - 0.645
    - 2.0
    - 0.59
    - 2.4
    - 0.5
    - 2.7
    - 0.41
    - 3.4
    - 0.22
    - 4.2
    - 0.13
    - 6.0
    - 0.04
    Soil_pH: 7.4
    Thickness: 20.0
  - CNRatioSOMI: 18.0
    CONDfromPF:
    - 0.0
    - 1.13
    - 1.0
    - 0.255
    - 1.3
    - 0.097
    - 1.5
    - -0.444
    - 1.7
    - -0.62
    - 2.0
    - -1.19
    - 2.4
    - -2.03
    - 2.7
    - -2.74
    - 3.0
    - -3.387
    - 3.4
    - -4.012
    - 3.7
    - -4.398
    - 4.0
    - -4.795
    - 4.2
    - -4.987
    CRAIRC: 0.1
    FSOMI: 0.001
    RHOD: 1.537
    SMfromPF:
    - -1.0
    - 0.73
    - 1.0
    - 0.675
    - 1.3
    - 0.66
    - 1.5
    - 0.645
    - 2.0
    - 0.59
    - 2.4
    - 0.5
    - 2.7
    - 0.41
    - 3.4
    - 0.22
    - 4.2
    - 0.13
    - 6.0
    - 0.04
    Soil_pH: 7.4
    SubSoilType: null
    Thickness: 25.0
  SurfaceConductivity: 75.0
